
version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd cms && npm install && npm run dev"
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - "3000:3000"
  api-local:
    build:
      context: .
      dockerfile: ./docker/api-local/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd api-local && python3 server.py"
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - "3001:3001"
  db:
    image: "amazon/dynamodb-local:latest"
    volumes:
      - db_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    working_dir: /home/dynamodblocal
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - "8000:8000"
    
volumes:
  db_data:
