import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <li><a href="/">色</a></li>
          <li><a href="/">はだ色</a></li>
          <li><a href="/">りんかく</a></li>
          <li><a href="/">め</a></li>
          <li><a href="/">かみがた</a></li>
        </ul>
        <button type="button" className={styles.reflect}>反映</button>
      </nav>

      <main className={styles.main}>
      </main>

    </div>
  )
}
