openapi: 3.0.0

info:
  title: バックエンドAPI
  description: 各情報を取得/操作するAPI
  version: 1.0.0

servers:
  - url: http://localhost:3002/
    description: Local開発環境

paths:
  /color:
    $ref: './paths/color.yml'
  /color/{id}:
    $ref: './paths/color.id.yml'
  /skin:
    $ref: './paths/skin.yml'
  /skin/{id}:
    $ref: './paths/skin.id.yml'
  /face:
    $ref: './paths/face.yml'
  /eye:
    $ref: './paths/eye.yml'
  /eye/{id}:
    $ref: './paths/eye.id.yml'
  /hair:
    $ref: './paths/hair.yml'
  /hair/{id}:
    $ref: './paths/hair.id.yml'
  /image:
    $ref: './paths/image.yml'
  /image/{id}:
    $ref: './paths/image.id.yml'
  /deploy:
    $ref: './paths/deployment.yml'

tags:
  - name: Color
    description: いろ情報を操作するAPI
  - name: Skin
    description: はだいろ情報を操作するAPI
  - name: Face
    description: りんかく情報を操作するAPI
  - name: Eye
    description: め情報を操作するAPI
  - name: Hair
    description: かみがた情報を操作するAPI
  - name: Image
    description: 画像データを操作するAPI
  - name: Deploy
    description: デプロイAPI

components:
  parameters:
    $ref: './components/parameters/index.yml'
  schemas:
    $ref: './components/schemas/index.yml'
